// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQZDum76oWRR6DuBOZzR60Vq3uBLEZOs',
    appId: '1:971056464608:web:a56211d7f694f0c61b0685',
    messagingSenderId: '971056464608',
    projectId: 'quizzle-be5a8',
    authDomain: 'quizzle-be5a8.firebaseapp.com',
    storageBucket: 'quizzle-be5a8.appspot.com',
    measurementId: 'G-P3Q4TDSNYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDvSzQ6dscL_xa9_Gdk-PRxJtu58GB_k',
    appId: '1:971056464608:android:967f89ea362bbcc61b0685',
    messagingSenderId: '971056464608',
    projectId: 'quizzle-be5a8',
    storageBucket: 'quizzle-be5a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLtuMSNIiu6m_wf_sUSnlFkYJEZlAnPo',
    appId: '1:971056464608:ios:fc9b4f6d2f0a4eef1b0685',
    messagingSenderId: '971056464608',
    projectId: 'quizzle-be5a8',
    storageBucket: 'quizzle-be5a8.appspot.com',
    iosClientId: '971056464608-hgkeq6tfn5frlv3nlh33vcbscvqgcoff.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
